version: '3'
services:
  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    volumes:
      - ./p3x-redis-ui-settings:/settings
    networks:
      - aath_network

  redis-cluster:
    image: redis:7
    container_name: cluster
    command: redis-cli --cluster create 174.96.0.101:6377 174.96.0.102:6378 174.96.0.103:6379 174.96.0.104:6380 174.96.0.105:6381 174.96.0.106:6382 --cluster-replicas 1 --cluster-yes
    environment:
      - REDISCLI_AUTH=${REDIS_PASSWORD}
    networks:
        aath_network:
          ipv4_address: 174.96.0.107
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
  redis-node-1:
      image: redis:7
      container_name: node1
      command: ["redis-server", "/conf/redis.conf", "--port 6377"]
      environment:
        - REDISCLI_AUTH=${REDIS_PASSWORD}
      ports:
        - 6377:6377
      volumes:
        - ./redis.conf:/conf/redis.conf
      networks:
        aath_network:
          ipv4_address: 174.96.0.101
  redis-node-2:
      image: redis:7
      container_name: node2
      command: ["redis-server", "/conf/redis.conf", "--port 6378"]
      environment:
        - REDISCLI_AUTH=${REDIS_PASSWORD}
      ports:
        - 6378:6378
      volumes:
        - ./redis.conf:/conf/redis.conf
      networks:
        aath_network:
          ipv4_address: 174.96.0.102
  redis-node-3:
      image: redis:7
      container_name: node3
      command: ["redis-server", "/conf/redis.conf", "--port 6379"]
      environment:
        - REDISCLI_AUTH=${REDIS_PASSWORD}
      ports:
        - 6379:6379
      volumes:
        - ./redis.conf:/conf/redis.conf
      networks:
        aath_network:
          ipv4_address: 174.96.0.103
  redis-node-4:
      image: redis:7
      container_name: node4
      command: ["redis-server", "/conf/redis.conf", "--port 6380"]
      environment:
        - REDISCLI_AUTH=${REDIS_PASSWORD}
      ports:
        - 6380:6380
      volumes:
        - ./redis.conf:/conf/redis.conf
      networks:
        aath_network:
          ipv4_address: 174.96.0.104
  redis-node-5:
      image: redis:7
      container_name: node5
      command: ["redis-server", "/conf/redis.conf", "--port 6381"]
      environment:
        - REDISCLI_AUTH=${REDIS_PASSWORD}
      ports:
        - 6381:6381
      volumes:
        - ./redis.conf:/conf/redis.conf
      networks:
        aath_network:
          ipv4_address: 174.96.0.105
  redis-node-6:
      image: redis:7
      container_name: node6
      command: ["redis-server", "/conf/redis.conf", "--port 6382"]
      environment:
        - REDISCLI_AUTH=${REDIS_PASSWORD}
      ports:
        - 6382:6382
      volumes:
        - ./redis.conf:/conf/redis.conf
      networks:
        aath_network:
          ipv4_address: 174.96.0.106


networks:
  aath_network:
    external: true

